apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-django
  labels:
    app: hello-django
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-django
  template:
    metadata:
      labels:
        app: hello-django
    spec:
      containers:
      - name: hello-django
        image: yashrajdighe/basic-django-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
